---
- name: Create Splunk directory
  file:
    path: /opt/splunk
    state: directory

- name: Download Splunk RPM
  get_url:
    url: "{{ splunk_download_url }}"
    dest: /opt/splunk/splunk.rpm
    mode: 744

- name: Install Splunk
  yum:
    name: /opt/splunk/splunk.rpm
    state: installed
