---
- name: Create Splunk directory
  file:
    path: /opt/splunk
    state: directory

- block: 
  - name: Copy Splunk RPM
    copy:
      src: files/splunk.rpm
      dest: /opt/splunk/splunk.rpm
      mode: 744
  
  rescue:
  - name: Download Splunk RPM
    get_url:
      url: "{{ splunk_download_url }}"
      dest: /opt/splunk/splunk.rpm
      mode: 744

- name: Install Splunk
  yum:
    name: /opt/splunk/splunk.rpm
    state: installed

- name: Start Splunkd
  command: "/opt/splunk/bin/splunk start --accept-license --seed-passwd {{ splunk_admin_pass }}"
  register: splunk_start_output

- name: Display splunk start output
  debug:
    msg: "{{ splunk_start_output }}"

- name: Create HTTP event collector directory
  file:
    state: directory
    path: /opt/splunk/etc/apps/splunk_httpinput/local
    owner: splunk
    group: splunk

- name: Push inputs.conf file to define token(s)
  template:
    src: hec_inputs.j2
    dest: /opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
    owner: splunk
    group: splunk
  notify: restart splunkd

- name: Create dashboard
  uri:
    url: "https://{{ inventory_hostname }}:8089/servicesNS/admin/search/data/ui/views/"
    user: admin
    password: "{{ splunk_admin_pass }}"
    body: "{{ lookup('file', 'dashboard_data.txt') }}"
    method: POST
    validate_certs: false
    status_code: [201,409]
  delegate_to: localhost
