---
- name: Create Splunk directory
  file:
    path: /opt/splunk
    state: directory

- block: 
  - name: Copy Splunk RPM
    copy:
      src: files/splunk.rpm
      dest: /opt/splunk/splunk.rpm
      mode: 744
  
  rescue:
  - name: Download Splunk RPM
    get_url:
      url: "{{ splunk_download_url }}"
      dest: /opt/splunk/splunk.rpm
      mode: 744

- name: Install Splunk
  yum:
    name: /opt/splunk/splunk.rpm
    state: installed

- name: Start Splunkd
  command: "/opt/splunk/bin/splunk start --accept-license --seed-passwd {{ splunk_admin_pass }}"
  register: splunk_start_output

- name: Display splunk start output
  debug:
    msg: "{{ splunk_start_output }}"

- name: Create HTTP event collector directory
  file:
    state: directory
    path: /opt/splunk/etc/apps/splunk_httpinput/local
    owner: splunk
    group: splunk

- name: Push inputs.conf file to define token(s)
  template:
    src: hec_inputs.j2
    dest: /opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
    owner: splunk
    group: splunk
  notify: restart splunkd






#As of now, these commands need to be run manually as the root user on the vagrant box.
#These commands interactively prompt for license agreement and admin credentials.
#- name: Enable Splunk service
#  command: "{{ item }}"
#  loop:
#  - /opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk
#  - /opt/splunk/bin/splunk start
#The Splunk web page can be accessed on port 8000
